# Generated by Django 4.2.30 on 2026-04-29 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_duration', models.CharField(help_text="e.g., '6 months', '12 weeks'", max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='accounts.careergoal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['career_goal', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_time', models.CharField(help_text="e.g., '2 weeks', '40 hours'", max_length=50)),
                ('estimated_hours', models.PositiveIntegerField(default=10, help_text='Estimated hours to complete this topic')),
                ('domain', models.CharField(choices=[('math', 'Mathematics'), ('coding', 'Coding'), ('stats', 'Statistics'), ('tools', 'Tools & Frameworks'), ('theory', 'Theory & Concepts'), ('practical', 'Practical Application'), ('soft_skills', 'Soft Skills'), ('domain_knowledge', 'Domain Knowledge')], default='coding', max_length=50)),
                ('is_milestone', models.BooleanField(default=False, help_text='Major milestone topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='roadmaps.topic')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('free', '🟢 Free'), ('paid', '🔵 Paid')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('coursera', 'Coursera'), ('udemy', 'Udemy'), ('kaggle', 'Kaggle'), ('github', 'GitHub'), ('medium', 'Medium'), ('freecodecamp', 'freeCodeCamp'), ('docs', 'Official Documentation'), ('book', 'Book'), ('article', 'Article'), ('interactive', 'Interactive Platform'), ('other', 'Other')], default='other', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified high-quality resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.topic')),
            ],
            options={
                'ordering': ['resource_type', 'platform', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='roadmaps.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
