# Generated by Django 4.2.30 on 2026-04-29 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('data_science', 'Data Science'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('cloud_devops', 'Cloud & DevOps'), ('cybersecurity', 'Cybersecurity'), ('ai_ml', 'AI & Machine Learning'), ('game_development', 'Game Development'), ('blockchain', 'Blockchain & Web3')], max_length=50)),
                ('icon', models.CharField(default='bi-briefcase', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('budget_mode', models.CharField(choices=[('free_only', 'Free Resources Only'), ('free_and_paid', 'Best Quality (Free + Paid)')], default='free_and_paid', max_length=20)),
                ('learning_style', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive Labs'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('mentor_bio', models.TextField(blank=True, max_length=500)),
                ('is_employer', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.careergoal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
